version: '3.2'
services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: ./webapi/Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      - MONGO_CONNECTION=mongodb://airflow-simple-user:airflow-simple-password@mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=airflow-simple-user
      - MONGO_INITDB_ROOT_PASSWORD=airflow-simple-password
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - airflow-mongo-db-volume:/data/db

volumes:
  airflow-mongo-db-volume: