name: oddsnexus
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - flask-caching
  - pymongo
  - python=3.10
  - pytest
  - requests
  - pip:
    - faust
    - pytest-asyncio
